//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lat_Quiz
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsSong
    {
        public int ID { get; set; }
        public string SongName { get; set; }
        public string ArtistName { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public string SongDescription { get; set; }
    }
}
